name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+-dev
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - master
      - v[0-9]+.[0-9]+-dev

jobs:
  test:
    name: Run drive tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Enable NPM cache
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Check NPM package lock version is updated
        run: npm run check-package # TODO: does this exist as an action already?

      - name: Install NPM dependencies
        run: npm ci

      - name: Run ESlinter
        run: npm run lint

      - name: Create dotenv file
        run: cp .env.example .env

      - name: Run tests
        run: npm run test:coverage

  test_suite:
    name: Run platform test suite
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Enable NPM cache
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

#      - uses: docker/setup-buildx-action@v1
#        id: buildx
#        with:
#          install: true

      - name: Cache Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          concurrency: 8

      - uses: strophy/gh-action-runtime-vars@v0.1.20
        if: ${{ contains(github.event.pull_request.body, '/set-var')}}

      - uses: dashevo/gh-action-start-local-network@master
        id: local_node
        with:
          drive-branch: $GITHUB_HEAD_REF
          dapi-branch: ${{ env.dapi-branch }}
          dashmate-branch: ${{ env.dashmate-branch }}
          install-sdk-version: ${{ env.install-sdk-version }}

      - uses: dashevo/gh-action-run-platform-test-suite@v0.1.1
        id: test_suite
        with:
          sdk-install: ${{ env.install-sdk-version }}
          faucet-private-key: ${{ env.faucet-private-key }}
          dpns-contract-id: ${{ env.dpns-contract-id }}
          dpns-top-level-identity-id: ${{ env.dpns-top-level-identity-id }}
          dpns-top-level-identity-private-key: ${{ env.dpns-top-level-identity-private-key }}
          version: ${{ env.platform-test-suite-branch }}

      - name: Show Docker logs
        if: ${{ failure() }}
        uses: jwalton/gh-docker-logs@v1
